name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: cmake .
    - name: build
      run: cmake --build .
    - name: test
      run: ctest .
