name: clang-format

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: format
      run: git diff -U0 --no-color HEAD^ | clang-format-diff -i -p1
    - name: status
      run: git status
