name: clang-format

on:
  pull_request:
    branches:
    - master

jobs:
  check-out:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: status
      run: git status
    - uses: docker.pkg.github.com/havogt/actions_playground/clang-format-diff:docker-base-layer
      volumes:
        - /:/workdir
    - name: status
      run: git status
