name: clang-format

on:
  pull_request:
    branches:
    - master

jobs:
  check-out:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: checkout
      run: git remote add upstream https://github.com/${GITHUB_REPOSITORY}.git && git fetch upstream
    - name: status
      run: git status
    - uses: havogt/actions_playground2/just-ls@master
    - uses: havogt/actions_playground2/git-diff@master
    - uses: docker://havogt/clang-format-diff:6.0.1
    - name: status
      run: git status
    - name: branch
      run: git ls-remote
    - name: commit
      run: git commit -am "file changed"
    - name: push
      run: git push
