name: clang-format

on:
  pull_request:
    branches:
    - master

jobs:
  check-out:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: status
      run: git status
    - uses: havogt/actions_playground2/git-diff@master
    - uses: havogt/actions_playground2/copy-a-file@master
    - name: status
      run: git status
    - name: commit
      run: git commit -am "file changed"
    - name: push
      run: git push
