name: clang-format

on:
  pull_request:
    branches:
    - master

jobs:
  check-out:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: status
      run: git status
    - uses: havogt/actions_playground2/copy-a-file@master
    - name: status
      run: git status
    - name: ls
      run: ls
    - name: pwd
      run: pwd
