name: clang-format

on:
  pull_request:
    branches:
    - master

jobs:
  check-out:

    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      run: git clone $GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
    - name: status
      run: git status
    - uses: havogt/actions_playground2/copy-a-file@master
    - uses: havogt/actions_playground2/just-ls@master
    - uses: havogt/actions_playground2/git-diff@master
    - name: status
      run: git status
    - name: branch
      run: git ls-remote
    - name: commit
      run: git commit -am "file changed"
    - name: push
      run: git push
