name: test event name
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: print event_name
      run: |
        echo ${{ github.event_name }}
    - name: print again
      if: github.event_name == 'workflow-dispatch'
      run: |
        echo ${{ github.event_name }}
    - name: and again
      if: ${{ github.event_name == 'workflow-dispatch' }}
      run: |
        echo ${{ github.event_name }}
  conditional_trigger:
    if: github.event_name == 'workflow-dispatch'
    name: runs_on_dispatch
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: print event_name
      run: |
        echo ${{ github.event_name }}
