name: test event name
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: print event_name
      run: |
        echo ${{ github.event_name }}
