name: test event name
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: print event_name
      run: |
        echo ${{ github.event_name }}
  conditional_trigger:
    name: runs_on_dispatch
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow-dispatch'
    steps:
    - name: print event_name
      run: |
        echo ${{ github.event_name }}
